# Generated by Django 4.0.1 on 2022-05-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='about_me',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='registration',
            name='my_skills',
            field=models.TextField(default='null'),
        ),
    ]
