# Generated by Django 4.0.1 on 2022-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0002_registration_about_me_registration_my_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='product_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
