# Generated by Django 4.0.1 on 2022-05-03 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0004_rename_product_image_registration_profile_image'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaints_text', models.TextField(default='null')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reply', models.TextField(default='null', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='open', max_length=15)),
                ('public_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.registration')),
                ('selected_mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanic.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('mechanic_user_id', models.IntegerField(default=0)),
                ('public_user_id', models.IntegerField(default=0)),
                ('messages_text', models.TextField(default='null')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('mechanic_user', 'Mechanic User'), ('user', 'User')], default='user', max_length=15)),
                ('complaints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.complaints')),
            ],
        ),
    ]
