# Generated by Django 4.0.1 on 2022-05-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_complaints_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='location_text',
            field=models.TextField(default='null'),
        ),
    ]
